name: Laravel Testing with Pest
on: [push, pull_request]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing

    steps:
      - uses: actions/checkout@v2

      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: "utf8" # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: "utf8_general_ci" # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql database: "testing_main" # Optional, default value is "test". The specified database which will be create
          mysql root password: "github-testing" # Required if "mysql user" exists. The password for the "mysql user"

      # - name: Start Redis
      #   uses: supercharge/redis-github-action@1.4.0
      #   with:
      #     redis-version: 7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_USERNAME: "root"
          DB_DATABASE: "testing_main"
          DB_PASSWORD: "github-testing"
          DB_HOST: "0.0.0.0"
          DB_PORT: "3306"
        run: php artisan cache:clear && php artisan config:clear && php artisan test
